openapi: 3.0.0
info:
  title: jalisconempleo
  description: Jalisco con empleo.
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1
    description: Optional server description, e.g. Main (production) server
paths:  
  /catalog/list:
    get:
      summary: Returns a list of categories.
      responses:
        '200':    
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string  
        sub_catagories:
          type: array
          items:
            $ref: '#/components/schemas/SubCategory'
          
    SubCategory:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string